name: Build & Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ether-runner-myzopotamia
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: docker buildx create --use
      
      - name: Debug Cache Contents
        run: |
          ls -lah /mnt/docker-cache
          df -h /mnt/docker-cache
          echo $DOCKER_BUILDKIT

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --cache-from type=local,src=/mnt/docker-cache \
            --cache-to type=local,dest=/mnt/docker-cache,mode=max \
            --load \
            -t blog \
            -f Dockerfile .
      
      - name: Push Docker image
        run: |
          export DOCKER_CONFIG=/tmp/docker-config
          docker tag blog rskupnik/ether:blog
          docker push rskupnik/ether:blog
