name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ether-runner-myzopotamia
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"